### ISSUE TITLE
feature idea - add buttons and event handlers

### ISSUE THREAD

**Issue by joshcorn** [amir-arad/tweakpane-table#1]
Love what you're doing with this project! I was looking to do something similar but I needed the ability to add a button for each row. I added that and also the ability to attach event handlers for each cell.

I'm not very good at TypeScript so I probably didn't implement it in the best way but I'm happy to share what I did it if it's of interest or related to your intent for the project. Regardless, thanks for the great work!

<img width="441" alt="Screen Shot 2023-02-20 at 1 13 35 AM" src="https://user-images.githubusercontent.com/5005597/220025237-26f7d20e-804c-49b6-a2c5-f24a54f88f42.png">

**Comment by amir-arad** [comment]
Thank you for taking the time to make this issue! it's so great to hear...
 I would love to add that table as an example, or review and make suggestions if you want

**Comment by amir-arad** [comment]
Ah! I missed that you suggested a feature, not a use case :)

I'm thinking maybe even in a larger scale: allow all inputs and monitoring, just like blades. also plugins support can be very much doable, assuming the plugin in question "behaves" in a row layout. WDYT?

**Comment by amir-arad** [comment]
new in v0.3.0 : 
![image](https://user-images.githubusercontent.com/6019373/222563117-d986dd9a-019b-42ff-94cd-c1ea84122e4e.png)

check out source code in
https://github.com/amir-arad/tweakpane-table/blob/main/test/advanced.html
